CREATE DATABASE arquiteturapin;

CREATE TABLE usuarios(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	login VARCHAR(8) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	CONSTRAINT USUARIOS_ID_PK PRIMARY KEY(id)
);

